// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/convoyinc/provider-redpanda/apis/acl/v1alpha1"
	v1alpha1cluster "github.com/convoyinc/provider-redpanda/apis/cluster/v1alpha1"
	v1alpha1topic "github.com/convoyinc/provider-redpanda/apis/topic/v1alpha1"
	v1alpha1user "github.com/convoyinc/provider-redpanda/apis/user/v1alpha1"
	v1alpha1apis "github.com/convoyinc/provider-redpanda/apis/v1alpha1"
	v1beta1 "github.com/convoyinc/provider-redpanda/apis/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1alpha1topic.SchemeBuilder.AddToScheme,
		v1alpha1user.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
